on:
  workflow_call:
    outputs:
      not-in-pr:
        description: The PR number if the branch is in one
        value: ${{ jobs.pr.outputs.not-in-pr }}

jobs:
  pr:
    runs-on: "ubuntu-latest"
    outputs:
      not-in-pr: ${{ steps.script.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: script
        if: github.event_name == 'push'
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.repo.owner + ':${{ github.ref_name }}'
            })
            if (prs.data.length) {
              console.log(`::notice ::Skipping CI on branch push as it is already run in PR #${prs.data[0]["number"]}`)
            } else {
              return "not-in-pr"
            }
